version: "3.7"

networks:
  default:
    driver: bridge

services:
  nginx:
    image: nginx:1.22-alpine
    ports:
      - 9091:91
      - 9092:92
      - 9093:93
    working_dir: /opt/www
    volumes:
      - ./docs/deploy/conf.d:/etc/nginx/conf.d/:rw
      - .:/opt/www
    networks:
      - default

  php:
    image: linnzh/php:7.4-alpine-fpm
    working_dir: /opt/www
    volumes:
      - .:/opt/www
    expose:
      - 9000
    ports:
      - 9345:2345
    networks:
      - default
